/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/candidato.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Candidato({ poseRef: _poseRef, ...props }) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/candidato.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  React.useEffect(() => {
    const run = names.find((name) => /run/i.test(name)) ?? names[0]
    const action = run ? actions[run] : undefined
    action?.reset().fadeIn(0.2).play()
    return () => action?.fadeOut(0.2)
  }, [actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="empty_1">
        <group name="FBX_Root">
          <primitive object={nodes.mixamorig4_Hips} />
          <group name="Ch12">
            <skinnedMesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.Ch12_body} skeleton={nodes.mesh_0.skeleton} />
            <skinnedMesh name="mesh_0_1" geometry={nodes.mesh_0_1.geometry} material={materials.Ch12_hair} skeleton={nodes.mesh_0_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/candidato.glb')
