/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/candidato.glb
*/

import { useEffect, useMemo, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useAnimations, useGLTF } from '@react-three/drei'
import { LoopOnce, LoopRepeat } from 'three'
import { SkeletonUtils } from 'three-stdlib'

const MODEL_URL = '/models/candidato.glb'
const FADE = 0.2

const RUN_NAMES = ['Run', 'Running', 'run', 'running', 'mixamo_com']
const JUMP_NAMES = ['Jump', 'Jumping', 'jump', 'jumping']

function findClip(actions, names) {
  const keys = Object.keys(actions)
  const byLower = new Map(keys.map((key) => [key.toLowerCase(), key]))
  for (const name of names) {
    if (actions[name]) return name
    const hit = byLower.get(name.toLowerCase())
    if (hit) return hit
  }
  return null
}

/**
 * Avatar de Miguel. `poseRef.current` es 'run' | 'jump' | 'idle'.
 * scale y rotation se pueden afinar desde el Jugador si el modelo sale pequeño o de espaldas.
 */
export function Candidato({ poseRef, ...props }) {
  const group = useRef()
  const pose = useRef(null)
  const { scene, animations } = useGLTF(MODEL_URL)
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  const clips = useMemo(() => {
    const run = findClip(actions, RUN_NAMES) ?? names[0] ?? null
    const jump = findClip(actions, JUMP_NAMES)
    return { run, jump: jump && jump !== run ? jump : null }
  }, [actions, names])

  useFrame(() => {
    const next = poseRef?.current ?? 'run'
    if (next === pose.current) return

    const runAction = clips.run ? actions[clips.run] : null
    if ((next === 'run' || next === 'jump') && !runAction && !actions[clips.jump]) return
    const jumpAction = clips.jump ? actions[clips.jump] : null

    if (next === 'idle') {
      runAction?.fadeOut(FADE)
      jumpAction?.fadeOut(FADE)
    } else if (next === 'jump' && jumpAction) {
      jumpAction.reset().setLoop(LoopOnce, 1)
      jumpAction.clampWhenFinished = true
      jumpAction.fadeIn(FADE).play()
      runAction?.fadeOut(FADE)
    } else if (next === 'run' && runAction && (pose.current !== 'jump' || jumpAction || !runAction.isRunning())) {
      // Sin clip de salto, la carrera sigue sonando: no la reiniciamos al caer.
      runAction.reset().setLoop(LoopRepeat, Infinity).fadeIn(FADE).play()
      jumpAction?.fadeOut(FADE)
    }

    pose.current = next
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="empty_1">
        <group name="FBX_Root">
          <primitive object={nodes.mixamorig4_Hips} />
          <group name="Ch12">
            <skinnedMesh
              name="mesh_0"
              geometry={nodes.mesh_0.geometry}
              material={materials.Ch12_body}
              skeleton={nodes.mesh_0.skeleton}
            />
            <skinnedMesh
              name="mesh_0_1"
              geometry={nodes.mesh_0_1.geometry}
              material={materials.Ch12_hair}
              skeleton={nodes.mesh_0_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

export const Model = Candidato

useGLTF.preload(MODEL_URL)
